---
- name: Install Homebrew
  shell: /bin/bash -c "NONINTERACTIVE=1 $(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
- name: Add Homebrew to terminal
  shell: |
    echo '# Set PATH, MANPATH, etc., for Homebrew.' >> {{ shell_config_path }}
    echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> {{ shell_config_path }}
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
- include_tasks: homebrew_fomulae.yml